version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: hive-postgres-dev
    environment:
      POSTGRES_DB: hive_db
      POSTGRES_USER: hive_user
      POSTGRES_PASSWORD: hive_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive_user -d hive_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Hive Application (Development)
  hive-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hive-app-dev
    environment:
      - DATABASE_URL={$DATABASE_URL:-postgresql://hive_user:hive_password@postgres:5432/hive_db}
      - NEXTAUTH_URL={$NEXTAUTH_URL:-http://100.97.107.124:3000}
      - NEXTAUTH_SECRET={$NEXTAUTH_SECRET:-bywYKt/K8MWQbRZQpUeujcTCzGctEsS0G8kfy1kqyDs=}
      - JWT_SECRET={$JWT_SECRET:-eb68e8048db53877963f8b4beb1fd55e72e1c6826777cd5a8694b28c21cd7f61f485bf3a6136293152584180f717fc840a10c27659ed1c14a29de07eb5e52148}
      - NODE_ENV={$NODE_ENV:-production}
      - GITHUB_CLIENT_ID={$GITHUB_CLIENT_ID:-Ov23li5LywKlITZ6eSzJ}
      - GITHUB_CLIENT_SECRET={GITHUB_CLIENT_SECRET:-2ee2e8a84251ee787a8729369535f12f3f7ae7dd}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data_dev: 
