import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  experimental: {
    optimizePackageImports: [
      "@xyflow/react",
      "@react-three/drei",
      "@react-three/fiber",
      "@sentry/nextjs",
      "@aws-sdk/client-s3",
      "@aws-sdk/s3-request-presigner",
      "@excalidraw/excalidraw",
      "ai",
      "d3",
      "react-syntax-highlighter",
      "react-hook-form",
      "@hookform/resolvers",
      "@dnd-kit/core",
      "@dnd-kit/sortable",
    ],
  },
  reactStrictMode: false,
  async redirects() {
    return [
      {
        source: "/w/:slug/stakgraph",
        destination: "/w/:slug/settings?tab=pool",
        permanent: false,
      },
      {
        source: "/w/:slug/learn/lingo",
        destination: "/w/:slug/lingo",
        permanent: true,
      },
    ];
  },
  distDir: process.env.NODE_ENV === "development" ? ".next-dev" : ".next",
  output: "standalone",
  // The offline legal-report export reads a build-time-generated CSS bundle
  // via `readFileSync(join(__dirname, "offline-report.css"))` (see
  // src/lib/run-report/export/offline-html.ts). Unlike the checked-in
  // viewer.js sitting next to it, this file is generated by
  // `npm run build:offline-css` (wired as `prebuild`) and is NOT guaranteed
  // to be picked up by @vercel/nft's static analysis the same way — it's
  // produced by a separate script, not authored source. Explicitly include
  // it so `next build`'s output-file-tracing copies it into
  // `.next/standalone`, and therefore into the Docker runner image.
  outputFileTracingIncludes: {
    "/**": ["src/lib/run-report/export/offline-report.css"],
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: process.env.NEXT_SKIP_TYPE_CHECK === "true",
  },

  serverExternalPackages: ["sharp", "zod"],
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "api.dicebear.com",
        port: "",
        pathname: "/**",
      },
      {
        protocol: "https",
        hostname: "avatars.githubusercontent.com",
        port: "",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;
