/**
 * `propose_code_change` tool — a real unified diff preview, generated by a
 * DETACHED strut run.
 *
 * Builds a `buildCodeChangeTools(ctx)` factory that fits the standard
 * capability-registry `buildTools` contract so it can be registered in
 * `capabilities.ts` under the `code_change` capability.
 *
 * ## What this tool does (strut path — the default)
 *
 * 1. Validates the caller-supplied `repositoryUrl` against the DB — must
 *    belong to the workspace. The workspace may own any number of repos; the
 *    named one is the single repo the change is for.
 * 2. Dispatches the `code-change-propose` strut workflow
 *    (`dispatchStrutRun`, kind `code_change_propose`): strut checks the repo
 *    out as the user (their GitHub token is pushed to strut as an ACTOR
 *    secret, never in the workflow `input`), a coding agent makes the change,
 *    and `git/diff` captures the working tree. The launch carries a callback
 *    URL, so the chat turn returns at once.
 * 3. Returns a PENDING `ProposalOutput` of `kind: "codeChange"` — empty
 *    diff, `preview: "pending"`, a link to the run in strut. The run's
 *    completion (`services/strut-runs/code-change-propose.ts`) runs hive's
 *    diff hygiene and patches the stored card in place with the diff (or an
 *    honest failure); Pusher + `reconcileProposalPreviews` flip it live.
 *
 * ## The synchronous path (`CODE_CHANGE_VIA_STRUT=false`)
 *
 * The previous shape — a read-only swarm `repo_agent` call polled INSIDE the
 * chat turn for up to ~10 min, hygiene + hash here, a READY card — is kept
 * for one release as a fallback and is deleted next.
 *
 * ## Security invariants
 *
 * - No PR is ever opened during preview: strut's checkout never holds a
 *   credential in the repository (token per command through a scrubbed env),
 *   so the agent's shell cannot push; the legacy path never registers
 *   `toolsConfig.create_pr`.
 * - A secrets hit in the diff discards it (in the completion handler, or
 *   here on the legacy path). The bytes never reach a log or transcript.
 * - Approval reads the diff from the `StrutRun` row, not the transcript
 *   (`handleApproval.ts`), so a forged conversation row cannot shadow a
 *   real proposal. The card's `payload.diff` is for display.
 * - The full diff on `payload.diff` is truncated on the way into model
 *   messages by `toModelMessages`, so a 200 KB diff does not re-enter LLM
 *   context on every turn.
 */

import crypto from "crypto";
import { tool, type ToolSet } from "ai";
import { z } from "zod";
import { db } from "@/lib/db";
import { repoAgent, REPO_AGENT_CANCELLED_MARKER } from "@/lib/ai/askTools";
import { cancelStrutRun, dispatchStrutRun, StrutDispatchError } from "@/services/strut-runs";
import {
  parseUnifiedDiff,
  enforceDiffCaps,
  scanForSecrets,
  unifiedDiffToActionResults,
} from "@/lib/github/diffHygiene";
import { getBifrostForLLM } from "@/services/bifrost/orchestrator";
import { parseGithubOwnerRepo } from "@/utils/repositoryParser";
import type { CapabilityContext } from "@/lib/ai/capabilities";
import {
  CODE_CHANGE_PROPOSE_KIND,
  CODE_CHANGE_PROPOSE_WORKFLOW,
  PROPOSE_CODE_CHANGE_TOOL,
} from "@/lib/proposals/types";
import type { ProposalOutput } from "@/lib/proposals/types";
import { EncryptionService } from "@/lib/encryption";
import { resolveOrgConversationRowId } from "@/services/org-canvas-conversation";

/**
 * The kill switch. Default = strut; `CODE_CHANGE_VIA_STRUT=false` (or `0`
 * / `off`) selects the synchronous swarm path for one release.
 */
export function codeChangeViaStrut(): boolean {
  const raw = (process.env.CODE_CHANGE_VIA_STRUT ?? "").trim().toLowerCase();
  return !(raw === "false" || raw === "0" || raw === "off");
}

// ─── Helpers ──────────────────────────────────────────────────────────────

/** SHA-256 hex digest of the diff bytes (UTF-8 encoded). */
function sha256Hex(text: string): string {
  return crypto.createHash("sha256").update(text, "utf8").digest("hex");
}

/**
 * Fields of the swarm's terminal result this tool reads. `content` is the
 * model's final text (every swarm). `preview` and `incomplete` come from
 * swarms that read the preview worktree themselves after the run (stakgraph
 * `captureWorktreeDiff`) and flag runs that never finished; older swarms
 * omit them, and the model's text is then the only source.
 *
 * `preview` is the ephemeral-run counterpart of the `pr` result on create_pr
 * runs, with the same `ok` / `failure` / `error` shape.
 */
interface SwarmPreviewResult {
  content?: unknown;
  preview?: { ok: true; diff: string; filesChanged: number } | { ok: false; failure: string; error: string };
  incomplete?: { reason: string };
}

function describeSwarmDiffError(e: { failure: string; error: string }): string {
  switch (e.failure) {
    case "no_changes":
      return (
        "The agent finished without changing any files in the repository, " +
        "so there is nothing to propose. Try a more specific prompt."
      );
    case "change_too_large":
      return (
        `The change is too large for a preview (${e.error}). ` +
        "Use `propose_feature` — the feature pipeline handles large changes."
      );
    case "secrets_detected":
      return (
        "The change contains patterns matching known credentials. " +
        "Review it manually and ensure no secrets are included before proposing."
      );
    default:
      return (
        `The swarm could not read the change from the preview worktree (${e.error}). ` +
        "Try again, or use `propose_feature`."
      );
  }
}

/**
 * Fetch the GitHub default branch for a repo via a plain authenticated GET.
 * Falls back to "main" on any error so a PAT scope issue doesn't block preview.
 * Exported for approval's strut path (the base branch of last resort).
 */
export async function fetchDefaultBranch(owner: string, repo: string, pat: string): Promise<string> {
  try {
    const url = `https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`;
    const res = await fetch(url, {
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
    });
    if (!res.ok) return "main";
    const data = (await res.json()) as { default_branch?: string };
    return data.default_branch ?? "main";
  } catch {
    return "main";
  }
}

function repoDisplayName(repositoryUrl: string, fallback: string | null | undefined): string {
  try {
    const { owner, repo } = parseGithubOwnerRepo(repositoryUrl);
    return `${owner}/${repo}`;
  } catch {
    return fallback ?? repositoryUrl;
  }
}

// ─── Strut path ───────────────────────────────────────────────────────────

/**
 * Dispatch the `code-change-propose` workflow and return the card PENDING.
 * Validation (workspace, membership, org, repo) has already run.
 */
async function proposeViaStrut(args: {
  ctx: CapabilityContext;
  workspace: { id: string; name: string; slug: string };
  repositoryUrl: string;
  repoName: string;
  title: string;
  body: string;
  prompt: string;
}): Promise<ProposalOutput | { error: string }> {
  const { ctx, workspace, repositoryUrl, repoName, title, body, prompt } = args;

  // The callback URL is built on the route-captured host; without it there
  // is nowhere for strut to deliver the diff. Same trap
  // `CapabilityContext.publicBaseUrl` documents — refuse, never guess.
  if (!ctx.publicBaseUrl) {
    return {
      error:
        "This deployment could not determine its public URL for the diff to be " +
        "delivered to. Please retry; if it persists, contact your administrator.",
    };
  }

  // The user's GitHub token, pushed to strut as THIS actor's secret so the
  // checkout runs as them. Never in the workflow input, never logged.
  const { getGithubUsernameAndPAT } = await import("@/lib/auth/nextauth");
  const githubProfile = await getGithubUsernameAndPAT(ctx.userId, workspace.slug);
  const pat = githubProfile?.token ?? null;

  // Delivery target: the validated org-canvas row (IDOR guard), if any.
  const conversationId = ctx.currentCanvasConversationId
    ? await resolveOrgConversationRowId({
        conversationId: ctx.currentCanvasConversationId,
        userId: ctx.userId,
        orgId: ctx.orgId,
      })
    : null;
  if (!conversationId) {
    return {
      error:
        "Code-change previews need a canvas conversation to deliver the diff to. " +
        "Ask again from the canvas chat.",
    };
  }

  const proposalId = crypto.randomUUID();
  const agentPrompt =
    `${prompt}\n\n` +
    `Repository: ${repositoryUrl}\n` +
    `Make the change directly in the working directory (edit files with the ` +
    `editor or bash). Do not commit, do not push, do not open a pull request, ` +
    `and do not print a diff — the change is captured from the working tree ` +
    `when you finish. Do not weaken or delete existing tests to make a change pass.`;

  let dispatched: Awaited<ReturnType<typeof dispatchStrutRun>>;
  try {
    dispatched = await dispatchStrutRun({
      workspaceId: workspace.id,
      userId: ctx.userId,
      kind: CODE_CHANGE_PROPOSE_KIND,
      workflow: CODE_CHANGE_PROPOSE_WORKFLOW,
      purpose: "code_change",
      input: { repo: repositoryUrl, prompt: agentPrompt },
      publicBaseUrl: ctx.publicBaseUrl,
      conversationId,
      proposalId,
      actorSecrets: { GITHUB_TOKEN: pat },
    });
  } catch (err) {
    const message = err instanceof StrutDispatchError ? err.message : "The code-change preview could not be started.";
    return {
      error:
        `${message} ` +
        "For large or multi-file changes, use `propose_feature` so the work " +
        "runs as a background task instead.",
    };
  }

  // The Stop button: register the run (keyed by the StrutRun id) so Stop
  // cancels it on strut. A Stop that landed before this registration
  // (pending-abort intent for this turn) cancels it right away.
  try {
    const { setActiveRun, notifyRunActive } = await import("@/services/canvas-active-runs-hooks");
    const { abortSelf } = await setActiveRun(
      conversationId,
      { requestId: dispatched.runId, workspaceId: workspace.id, startedAt: new Date().toISOString() },
      dispatched.runId, // turnId fallback
    );
    if (abortSelf) {
      await cancelStrutRun({
        id: dispatched.runId,
        swarmId: dispatched.swarmId,
        workflow: CODE_CHANGE_PROPOSE_WORKFLOW,
        strutRunId: dispatched.strutRunId,
      });
    }
    await notifyRunActive(conversationId, true);
  } catch (err) {
    console.warn("[propose_code_change] active-run registration failed (non-fatal)", {
      runId: dispatched.runId,
      error: err instanceof Error ? err.message : String(err),
    });
  }

  const output: ProposalOutput = {
    kind: "codeChange",
    proposalId,
    payload: {
      workspaceId: workspace.id,
      workspaceSlug: workspace.slug,
      repositoryUrl,
      title: title.replace(/[\r\n]+/g, " ").trim(),
      body,
      diff: "",
      diffSha256: "",
      filesChanged: 0,
      preview: "pending",
      pending: {
        runId: dispatched.runId,
        strutRunId: dispatched.strutRunId,
        swarmId: dispatched.swarmId,
        runUrl: dispatched.runUrl,
      },
    },
    // Stamped server-side from the tool's own context — never a caller
    // input. Approval checks it against the STORED transcript AND the
    // StrutRun row's `userId`.
    originatorUserId: ctx.userId,
    rationale: `Generating a diff for '${title}' — this card will update when it is ready.`,
    meta: {
      repoName,
      workspaceName: workspace.name,
      workspaceSlug: workspace.slug,
    },
  };
  return output;
}

// ─── Tool factory ─────────────────────────────────────────────────────────

export function buildCodeChangeTools(ctx: CapabilityContext): ToolSet {
  return {
    [PROPOSE_CODE_CHANGE_TOOL]: tool({
      description:
        "Generate a real unified diff preview for a proposed code change " +
        "in one repository, then surface it as an approvable proposal card. " +
        "Returns immediately: a coding agent makes the change in the background " +
        "and the card fills in with the diff when it is ready — do not poll and " +
        "do not call this again for the same change. No PR is opened during preview. " +
        "The user reviews the diff and clicks Approve to land it as a PR. " +
        "Works in workspaces with any number of repositories: name the target " +
        "in `repositoryUrl`. Pick it from where the code you are changing " +
        "actually lives — if you have not established that, investigate with " +
        "`repo_agent` first, or ask the user. " +
        "Use `propose_feature` instead when the change spans MORE THAN ONE " +
        "repository, when you cannot tell which repository it belongs in, or " +
        "for database migrations, schema changes, and large multi-file refactors.",
      inputSchema: z.object({
        workspaceSlug: z.string().describe("The workspace slug that owns the target repository."),
        repositoryUrl: z
          .string()
          .url()
          .describe(
            "HTTPS URL of the single GitHub repository to patch " +
              "(e.g. https://github.com/org/repo). " +
              "Must be registered in the workspace — the workspace may own " +
              "others. Choose the one containing the files you are changing; " +
              "if that is unclear, use `propose_feature` instead of guessing.",
          ),
        title: z
          .string()
          .min(1)
          .max(256)
          .describe("Short PR title (no leading dash). " + "The [Jamie] prefix is added automatically."),
        body: z.string().max(65536).default("").describe("PR body / description (markdown)."),
        prompt: z
          .string()
          .min(1)
          .describe(
            "Instruction for the coding agent describing the exact change " +
              "to make. Be specific: filenames, function names, what to add/remove. " +
              "The agent applies the change in a checkout; the diff is captured " +
              "from the working tree automatically.",
          ),
      }),
      execute: async ({
        workspaceSlug,
        repositoryUrl,
        title,
        body,
        prompt,
      }): Promise<ProposalOutput | { error: string }> => {
        // ── 1. Workspace + repository validation ──────────────────────
        const workspace = await db.workspace.findUnique({
          where: { slug: workspaceSlug },
          select: {
            id: true,
            name: true,
            sourceControlOrg: { select: { id: true } },
            swarm: { select: { swarmUrl: true, swarmApiKey: true } },
            members: {
              where: { userId: ctx.userId },
              select: { userId: true },
            },
          },
        });
        if (!workspace) {
          return { error: `Workspace '${workspaceSlug}' not found.` };
        }

        // Authorization: verify ctx.userId is a member of this workspace
        // before any credentials or swarm keys are accessed.
        if (workspace.members.length === 0) {
          return {
            error: "You do not have access to workspace '" + workspaceSlug + "'.",
          };
        }

        // Org-membership check: ctx.orgId is the SourceControlOrg.id the
        // caller already validated. Refuse cross-org requests.
        if (ctx.orgId && workspace.sourceControlOrg && workspace.sourceControlOrg.id !== ctx.orgId) {
          return {
            error: "Repository does not belong to the active org. " + "Use `propose_feature` for cross-org changes.",
          };
        }

        // Validate the requested repositoryUrl belongs to this workspace.
        const dbRepo = await db.repository.findFirst({
          where: { workspaceId: workspace.id, repositoryUrl },
          select: { id: true, name: true, repositoryUrl: true },
        });
        if (!dbRepo) {
          return {
            error:
              `Repository '${repositoryUrl}' is not registered in ` +
              `workspace '${workspaceSlug}'. Add it via workspace Settings first.`,
          };
        }

        // NOTE: the workspace's repository COUNT is deliberately not checked.
        // `repositoryUrl` is a required input that has just been validated
        // against this workspace, and it is the single explicit `repo_url` sent
        // to both the read-only preview below and `create_pr` at approval time.
        // That is the only thing the swarm contract actually requires —
        // `LAND_CHANGE_ERR_MULTI_REPO` refuses a comma-separated list or an
        // omitted repo_url, not a workspace that happens to own several repos
        // (`Repository` is workspace-scoped, with no binding to the Swarm).
        //
        // Most workspaces have more than one repo, so gating on the count made
        // the tool unreachable for the common case while adding no safety: a
        // wrong repo choice is a judgment error, and it is caught where every
        // other judgment error in this flow is caught — the approval card,
        // which names the repo next to the diff and requires an explicit click.

        // ── Strut path (default): dispatch, return a pending card ───────
        if (codeChangeViaStrut()) {
          return proposeViaStrut({
            ctx,
            workspace: { id: workspace.id, name: workspace.name, slug: workspaceSlug },
            repositoryUrl,
            repoName: repoDisplayName(repositoryUrl, dbRepo.name),
            title,
            body,
            prompt,
          });
        }

        // ── 2. Swarm credentials (legacy synchronous path) ─────────────
        if (!workspace.swarm?.swarmUrl || !workspace.swarm.swarmApiKey) {
          return {
            error: `Swarm not configured for workspace '${workspaceSlug}'.`,
          };
        }

        let swarmApiKey: string;
        try {
          swarmApiKey = EncryptionService.getInstance().decryptField("swarmApiKey", workspace.swarm.swarmApiKey);
        } catch {
          return {
            error: "Failed to decrypt swarm credentials for this workspace.",
          };
        }

        const swarmUrlRaw = workspace.swarm.swarmUrl;
        const swarmUrlObj = new URL(swarmUrlRaw);
        const swarmUrl = swarmUrlRaw.includes("localhost")
          ? "http://localhost:3355"
          : `https://${swarmUrlObj.hostname}:3355`;

        // ── 3. GitHub PAT ──────────────────────────────────────────────
        const { getGithubUsernameAndPAT } = await import("@/lib/auth/nextauth");
        const githubProfile = await getGithubUsernameAndPAT(ctx.userId, workspaceSlug);
        const pat = githubProfile?.token ?? "";

        // ── 4. Fetch live baseBranchDisplay from GitHub ────────────────
        // Do NOT use Repository.branch — it's Hive-configured and may differ
        // from what the swarm will actually branch from.
        let baseBranchDisplay = "main";
        try {
          const { owner, repo } = parseGithubOwnerRepo(repositoryUrl);
          baseBranchDisplay = await fetchDefaultBranch(owner, repo, pat);
        } catch {
          // Non-fatal: display value only.
        }

        // ── 5. Bifrost routing for cost attribution ────────────────────
        const bifrost = await getBifrostForLLM(
          {
            workspaceId: workspace.id,
            workspaceSlug,
            userId: ctx.userId,
          },
          { agentName: "repo-agent" },
        );

        // ── 6. Abort/active-run hooks ──────────────────────────────────
        const convId = ctx.currentCanvasConversationId;
        let activeRequestId: string | undefined;
        const hooks = convId
          ? await (async () => {
              const { setActiveRun, isAbortRequestedForRun, notifyRunActive } =
                await import("@/services/canvas-active-runs-hooks");
              return {
                onRequestId: async (requestId: string) => {
                  activeRequestId = requestId;
                  await setActiveRun(
                    convId,
                    {
                      requestId,
                      workspaceId: workspace.id,
                      startedAt: new Date().toISOString(),
                    },
                    requestId, // turnId fallback
                  );
                  await notifyRunActive(convId, true);
                },
                isAbortRequested: async () => isAbortRequestedForRun(convId, activeRequestId ?? ""),
              };
            })()
          : undefined;

        // ── 7. READ-ONLY repo_agent call ───────────────────────────────
        // `toolsConfig.create_pr` is INTENTIONALLY ABSENT — structural
        // guarantee that no PR is opened during this preview run.
        // The swarm reads the diff from the preview worktree itself when the
        // run finishes (`diff` on the result), so the diff the model pastes
        // is a fallback for swarms that predate that. It stages first:
        // `git diff HEAD` alone omits new files.
        const agentPrompt =
          `${prompt}\n\n` +
          `Repository: ${repositoryUrl}\n` +
          `IMPORTANT: This is a READ-ONLY preview run. Do NOT push any branch ` +
          `or open a pull request. Apply the change directly in the working tree ` +
          `(bash, or the file editor). When every edit is done, run: ` +
          `git add -A && git diff --cached\n` +
          `and output that unified diff (starting with "--- " / "+++ ") as your ` +
          `final answer, with no commentary after it.`;

        let rawResult: Record<string, string> | typeof REPO_AGENT_CANCELLED_MARKER;
        try {
          rawResult = await repoAgent(
            swarmUrl,
            swarmApiKey,
            {
              repo_url: repositoryUrl,
              prompt: agentPrompt,
              pat,
              // Throwaway detached worktree: the preview can never dirty
              // the shared checkout (or push — bash is confined and
              // tokens are blanked on ephemeral runs).
              ephemeral: true,
              // `toolsConfig.create_pr` deliberately absent.
            },
            bifrost,
            hooks,
          );
        } catch (err) {
          const detail = err instanceof Error && err.message ? ` (${err.message})` : "";
          return {
            error:
              `The code-change preview failed${detail}. ` +
              "For large or multi-file changes, use `propose_feature` so the " +
              "work runs as a background task instead.",
          };
        } finally {
          if (convId && activeRequestId) {
            const { clearActiveRun, notifyRunActive } = await import("@/services/canvas-active-runs-hooks");
            const { wasLast } = await clearActiveRun(convId, activeRequestId).catch(() => ({ wasLast: true }));
            if (wasLast) await notifyRunActive(convId, false).catch(() => {});
          }
        }

        if (rawResult === REPO_AGENT_CANCELLED_MARKER) {
          return {
            error: "Code-change preview was cancelled. " + "For large changes, use `propose_feature` instead.",
          };
        }

        // ── 8. Take the diff ───────────────────────────────────────────
        const swarm = rawResult as unknown as SwarmPreviewResult;

        // The run ended without a proper termination (stall, truncation,
        // stream error). Whatever text came back is narration, and the
        // worktree may hold a half-applied change. Not a proposal.
        if (swarm.incomplete) {
          return {
            error:
              `The agent stopped before finishing the change (${swarm.incomplete.reason}). ` +
              "No proposal was created. Try again with a more specific prompt, " +
              "or use `propose_feature` for larger changes.",
          };
        }

        // A swarm that read the worktree and found a reason there is no diff
        // is believed over anything the model pasted into its answer.
        if (swarm.preview && !swarm.preview.ok) {
          return { error: describeSwarmDiffError(swarm.preview) };
        }

        // Newer swarms return the worktree's own diff — ground truth, new
        // files included. Older swarms return only the model's text, so the
        // regex extraction stays as the fallback.
        let rawDiff: string;
        if (swarm.preview?.ok && swarm.preview.diff.trim()) {
          rawDiff = swarm.preview.diff.trimEnd();
        } else {
          const agentOutput = typeof swarm.content === "string" ? swarm.content : JSON.stringify(rawResult);
          // Grab the first unified-diff block from the output.
          const diffMatch = agentOutput.match(/(---[ \t][^\n]+\n\+\+\+[ \t][^\n]+[\s\S]*)/);
          rawDiff = diffMatch ? diffMatch[1].trimEnd() : agentOutput.trim();
        }

        // ── 9. diffHygiene validation ──────────────────────────────────
        const parseResult = parseUnifiedDiff(rawDiff);
        if (!parseResult.ok) {
          return {
            error:
              `The swarm did not return a valid unified diff ` +
              `(${parseResult.code}: ${parseResult.message}). ` +
              "Try a more specific prompt, or use `propose_feature` for " +
              "complex changes.",
          };
        }

        const capsResult = enforceDiffCaps(rawDiff);
        if (!capsResult.ok) {
          return {
            error:
              `Diff exceeds size limits (${capsResult.code}). ` +
              "Use `propose_feature` — the feature pipeline handles large changes.",
          };
        }

        const secretsResult = scanForSecrets(rawDiff);
        if (!secretsResult.ok) {
          // Hard rule: never return or persist a diff containing credentials.
          // The bytes are discarded here.
          return {
            error:
              "The diff contains patterns matching known credentials. " +
              "Review the change manually and ensure no secrets are included " +
              "before proposing.",
          };
        }

        // ── 10. diffSha256 ─────────────────────────────────────────────
        const diffSha256 = sha256Hex(rawDiff);

        // ── 11. Convert diff to ActionResult[] for DiffContent card ────
        let repoName: string;
        try {
          const { owner, repo } = parseGithubOwnerRepo(repositoryUrl);
          repoName = `${owner}/${repo}`;
        } catch {
          repoName = dbRepo.name ?? repositoryUrl;
        }

        const diffs = unifiedDiffToActionResults(rawDiff, repoName);

        // ── 12. Build ProposalOutput (kind: "codeChange") ──────────────
        const proposalId = crypto.randomUUID();

        // The payload carries the full diff for the approval handler to
        // re-verify and forward to the swarm's create_pr.
        const output: ProposalOutput = {
          kind: "codeChange",
          proposalId,
          payload: {
            workspaceId: workspace.id,
            workspaceSlug,
            repositoryUrl,
            title: title.replace(/[\r\n]+/g, " ").trim(),
            body,
            diff: rawDiff,
            diffSha256,
            filesChanged: diffs.length,
            baseBranchDisplay,
          },
          // Stamped server-side from the tool's own context — never a caller
          // input. The approval handler reads this back off the STORED
          // transcript to enforce that only the originator can approve.
          originatorUserId: ctx.userId,
          rationale:
            `Preview diff for '${title}' — ${diffs.length} file(s) changed. ` +
            `Base branch: ${baseBranchDisplay}. ` +
            `Diff SHA-256: ${diffSha256.slice(0, 16)}…`,
          meta: {
            repoName,
            workspaceName: workspace.name,
            workspaceSlug,
          },
        };

        // ── 13. Return ─────────────────────────────────────────────────
        // `payload.diff` carries the FULL bytes: they are persisted on
        // `CanvasChatMessage.toolCalls[].output`, which is the only place
        // the approved diff lives, and the approval handler re-hashes them
        // against `diffSha256`. Keeping the model's context from carrying
        // those bytes on every later turn is handled at the replay boundary
        // (`toModelMessages` in `@/lib/ai/conversationHelpers`), which
        // truncates the diff on the way into model messages while leaving
        // the stored row intact.
        return output;
      },
    }),
  };
}
