/**
 * Canvas projection types.
 *
 * The big idea (see `docs/plans/org-canvas.md`): a canvas the user reads
 * is the merge of **authored content** (what a human or LLM drew) and
 * **projected content** (live DB entities like workspaces and features).
 * Only the authored half is persisted; the live half is re-computed on
 * every read.
 *
 * This file defines the shapes. The merge/split logic lives in `./io`.
 */
import type {
  CanvasData,
  CanvasEdge,
  CanvasLane,
  CanvasNode,
} from "system-canvas";

/**
 * What gets persisted in `Canvas.data` (one row per `(orgId, ref)`).
 *
 * Four fields. `nodes` and `edges` already existed in v0; `positions`
 * and `hidden` are the v1 additions that let the blob carry per-canvas
 * layout and visibility decisions for live nodes without duplicating
 * the entities themselves.
 *
 * Keep this in lockstep with the plan doc. Adding a field here is a
 * persistence change — prefer computing on read when you can.
 */
export interface CanvasBlob {
  /**
   * Authored nodes only. Their ids are generated by the canvas library
   * and never carry a `<kind>:` prefix — that's how the splitter tells
   * them apart from live ids.
   */
  nodes: CanvasNode[];
  /**
   * Edges between any two nodes. Endpoints may be authored ids, live
   * ids (e.g. `ws:abc`), or a mix. Persisted verbatim; referential
   * integrity is enforced on read (dangling edges are silently dropped
   * from the merge, but stay in the blob until write-time pruning).
   */
  edges: CanvasEdge[];
  /**
   * Per-canvas overlay for live nodes. Key = live id (e.g. `ws:abc`);
   * value = `{ x, y, width?, height? }`. A missing key means "use the
   * projector's defaults." Width/height are optional — set only when
   * the user has explicitly resized the card; otherwise the renderer
   * falls back to the category's theme default. Never contains
   * authored ids: those nodes carry their own coords/size directly.
   *
   * Field name kept as `positions` for backward-compat with existing
   * blobs; semantically it's now "live-node overlay."
   */
  positions?: Record<
    string,
    { x: number; y: number; width?: number; height?: number }
  >;
  /**
   * Live nodes the user has chosen to hide on this canvas. Absence from
   * this list means visible. Unrelated to deletion — hidden entities
   * still exist in the DB and on other canvases.
   */
  hidden?: string[];
  /**
   * Per-canvas list of feature ids the user (or agent) has pinned onto
   * this canvas. Today the only consumer is the workspace sub-canvas
   * (`ref` starting with `ws:`): the workspace projector emits one
   * `feature:<id>` card per id in this list, in order. Other canvases
   * ignore the field — feature projection on an initiative canvas is
   * driven by `Feature.initiativeId`, not by this overlay, so the user
   * doesn't need to "add" features there manually.
   *
   * **Why an explicit list, not auto-projection.** The workspace
   * sub-canvas previously auto-projected loose features (cap 25). For
   * backlog-heavy workspaces that capped slice was both noisy AND
   * incomplete; the auto-fit then squeezed the ops cards (repos,
   * services) until they were unreadable. Switching to "user chooses
   * which features show up here" keeps the workspace canvas useful as
   * an ops surface while still letting people pin a small focused set
   * of in-flight features when that adds value.
   *
   * Same write-path treatment as `hidden`: `splitCanvas` preserves the
   * previous value untouched, so autosave never clobbers pins. Toggling
   * goes through dedicated `assignFeatureOnCanvas` /
   * `unassignFeatureOnCanvas` helpers.
   */
  assignedFeatures?: string[];
}

/**
 * A scope describes "which canvas am I looking at." Stored serialized
 * in `Canvas.ref`; parsed on every read/write via `parseScope`.
 *
 * Adding a new scope kind takes three edits:
 *   1. Extend this union.
 *   2. Teach `parseScope` the new prefix.
 *   3. Write a `Projector` that emits live nodes for it.
 */
export type Scope =
  | { kind: "root" }
  /**
   * Legacy authored-sub scope from the pre-cutover "objectives" plan
   * (see `docs/plans/org-canvas.md`). Drillable authored objectives
   * are gone, but we keep parsing the `node:<id>` prefix so any
   * orphaned blobs round-trip without errors. Projectors no-op on it.
   */
  | { kind: "authored"; nodeId: string }
  | { kind: "workspace"; workspaceId: string }
  | { kind: "initiative"; initiativeId: string }
  /** Reserved — feature deep-dive projection is unshipped. */
  | { kind: "feature"; featureId: string }
  /**
   * A ref we don't recognize. We still accept it — it addresses a
   * canvas but has no projection. This covers pre-v1 authored
   * sub-canvases whose refs are raw node ids (no `node:` prefix), and
   * lets ad-hoc slug-style refs keep working. Projectors no-op; the
   * blob is round-tripped verbatim.
   */
  | { kind: "opaque"; ref: string };

/**
 * What a projector emits.
 *
 * - `nodes` — the live nodes produced for this scope.
 * - `edges` — optional synthetic edges projected from DB membership
 *   (e.g. `feature:<id> → milestone:<id>` to express "this feature
 *   belongs to this milestone"). Their ids must be prefixed with
 *   `synthetic:` so `splitCanvas` can filter them on save — they
 *   never round-trip into the authored blob, since the relationship
 *   they encode lives in the DB. User-drawn edges between the same
 *   endpoints are intercepted client-side and turned into DB
 *   mutations rather than authored edges, so the two never coexist
 *   for the same relationship.
 * - `rollups` — keyed by live id and merged into the live node's
 *   `customData`; existing authored keys win (see the "manual
 *   customData wins; rollup fills the gaps" rule in the plan).
 * - `columns` / `rows` — optional background bands rendered behind
 *   the canvas. Used for timeline/swim-lane decorations (e.g. the
 *   "Past Due / This Quarter / Next Quarter / Later" bands on the
 *   milestone timeline). They are **decorative chrome only** —
 *   the renderer paints them as tinted backgrounds + headers but
 *   does NOT snap nodes to them. Cards keep their projector- or
 *   user-assigned positions independently. Only one projector per
 *   scope should emit lanes; the merge picks the first non-empty
 *   set it sees.
 */
export interface ProjectionResult {
  nodes: CanvasNode[];
  edges?: CanvasEdge[];
  rollups?: Record<string, Record<string, unknown>>;
  columns?: CanvasLane[];
  rows?: CanvasLane[];
}

/**
 * Read-only slice of the authored blob handed to projectors that need
 * to see per-canvas overlays. Today the only consumer is
 * `workspaceProjector`, which reads `assignedFeatures` to decide which
 * feature cards to emit. Projectors that don't need the blob accept
 * an undefined/empty context and behave identically to before.
 *
 * Pass-through-only on purpose: projectors must NOT mutate the blob,
 * and adding a non-blob field here (e.g. "user id of the caller")
 * would couple projection to request context. If a future need is
 * neither blob-derived nor `(scope, orgId)`-derived, prefer a new
 * argument over expanding this type.
 */
export interface ProjectorContext {
  /** Per-canvas pinned feature ids, from `CanvasBlob.assignedFeatures`. */
  assignedFeatures?: string[];
}

export interface Projector {
  /**
   * Returns `{ nodes: [] }` when the scope doesn't apply.
   *
   * `context` is optional so existing projectors keep compiling
   * without edits; it carries blob-derived inputs (`assignedFeatures`
   * today) that the framework reads once per `readCanvas` and shares
   * across every projector.
   */
  project(
    scope: Scope,
    orgId: string,
    context?: ProjectorContext,
  ): Promise<ProjectionResult>;
}

/** Re-export the library's runtime shape so callers don't need two imports. */
export type { CanvasData, CanvasEdge, CanvasLane, CanvasNode };
