/**
 * Canvas projection types.
 *
 * The big idea (see `docs/plans/org-canvas.md`): a canvas the user reads
 * is the merge of **authored content** (what a human or LLM drew) and
 * **projected content** (live DB entities like workspaces and features).
 * Only the authored half is persisted; the live half is re-computed on
 * every read.
 *
 * This file defines the shapes. The merge/split logic lives in `./io`.
 */
import type { CanvasData, CanvasEdge, CanvasNode } from "system-canvas";

/**
 * What gets persisted in `Canvas.data` (one row per `(orgId, ref)`).
 *
 * Four fields. `nodes` and `edges` already existed in v0; `positions`
 * and `hidden` are the v1 additions that let the blob carry per-canvas
 * layout and visibility decisions for live nodes without duplicating
 * the entities themselves.
 *
 * Keep this in lockstep with the plan doc. Adding a field here is a
 * persistence change — prefer computing on read when you can.
 */
export interface CanvasBlob {
  /**
   * Authored nodes only. Their ids are generated by the canvas library
   * and never carry a `<kind>:` prefix — that's how the splitter tells
   * them apart from live ids.
   */
  nodes: CanvasNode[];
  /**
   * Edges between any two nodes. Endpoints may be authored ids, live
   * ids (e.g. `ws:abc`), or a mix. Persisted verbatim; referential
   * integrity is enforced on read (dangling edges are silently dropped
   * from the merge, but stay in the blob until write-time pruning).
   */
  edges: CanvasEdge[];
  /**
   * Per-canvas placement for live nodes. Key = live id (e.g. `ws:abc`);
   * value = `{ x, y }`. A missing key means "use the projector's
   * default placement." Never contains authored ids — those nodes carry
   * their own `x` / `y` directly.
   */
  positions?: Record<string, { x: number; y: number }>;
  /**
   * Live nodes the user has chosen to hide on this canvas. Absence from
   * this list means visible. Unrelated to deletion — hidden entities
   * still exist in the DB and on other canvases.
   */
  hidden?: string[];
}

/**
 * A scope describes "which canvas am I looking at." Stored serialized
 * in `Canvas.ref`; parsed on every read/write via `parseScope`.
 *
 * Adding a new scope kind takes three edits:
 *   1. Extend this union.
 *   2. Teach `parseScope` the new prefix.
 *   3. Write a `Projector` that emits live nodes for it.
 */
export type Scope =
  | { kind: "root" }
  | { kind: "authored"; nodeId: string }
  | { kind: "workspace"; workspaceId: string }
  | { kind: "feature"; featureId: string }
  /**
   * A ref we don't recognize. We still accept it — it addresses a
   * canvas but has no projection. This covers pre-v1 authored
   * sub-canvases whose refs are raw node ids (no `node:` prefix), and
   * lets ad-hoc slug-style refs keep working. Projectors no-op; the
   * blob is round-tripped verbatim.
   */
  | { kind: "opaque"; ref: string };

/**
 * What a projector emits. `rollups` is keyed by live id and merged into
 * the live node's `customData`; existing authored keys win (see the
 * "manual customData wins; rollup fills the gaps" rule in the plan).
 */
export interface ProjectionResult {
  nodes: CanvasNode[];
  rollups?: Record<string, Record<string, unknown>>;
}

export interface Projector {
  /** Returns `{ nodes: [] }` when the scope doesn't apply. */
  project(scope: Scope, orgId: string): Promise<ProjectionResult>;
}

/** Re-export the library's runtime shape so callers don't need two imports. */
export type { CanvasData, CanvasEdge, CanvasNode };
