name: Next.js CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache Prisma Binaries
      uses: actions/cache@v4
      with:
        path: ~/.cache/prisma
        key: ${{ runner.os }}-prisma-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-prisma-

    - name: Install Dependencies
      run: npm install

    - name: Generate Prisma Client with Retry
      run: npx prisma migrate dev

    - name: Build Next.js App
      run: npm run build
